# Generated by Django 2.1.3 on 2018-11-28 00:10

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
                ('candidate_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('member_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='semester',
            managers=[
                ('semester_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='id_candidates',
        ),
        migrations.AddField(
            model_name='candidate',
            name='semester_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webApp.Semester'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='postulation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
