# Generated by Django 2.1.3 on 2018-11-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20181127_1910'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='semester',
            managers=[
            ],
        ),
    ]
