# Generated by Django 2.1.3 on 2018-11-29 13:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_auto_20181129_0757'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='candidate',
            managers=[
                ('candidate_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('member_', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='semester',
            managers=[
                ('semester_', django.db.models.manager.Manager()),
            ],
        ),
    ]
