# Generated by Django 2.2.5 on 2019-09-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_auto_20181129_2001'),
        ('webApp', '0004_auto_20181129_0816'),
    ]

    operations = [
    ]
